project:
  type: website

website:
  title: "Bea Milz"
  page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Beatriz Milz. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/beatrizmilz/blog-en
      - icon: twitter
        href: https://twitter.com/BeaMilz
      - icon: envelope
        href: mailto:milz.bea@gmail.com
  navbar:
    right:
      - about.qmd
      - text: Posts
        href: /
      - text: Talks
        href: /talks/
      - text: Resume
        href: https://beatrizmilz.github.io/resume/index.pdf
      - text: My blog in Portuguese
        href: https://beatrizmilz.com/blog/

      - icon: github
        href: https://github.com/beatrizmilz/blog-en
      - icon: twitter
        href: https://twitter.com/BeaMilz

format:
  html:
    theme: journal
    css: styles.css

editor: visual

comments:
  giscus:
    repo: beatrizmilz/blog-en
