project:
  type: website

website:
  title: "Bea Milz"
  page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Beatriz Milz. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/beatrizmilz/
      - icon: twitter
        href: https://twitter.com/BeaMilz
      - icon: envelope
        href: mailto:milz.bea@gmail.com
  twitter-card:
    creator: "@beamilz"
    card-style: summary_large_image
  navbar:
    right:
      - about.qmd
      - text: Posts
        href: /
      - text: Talks
        href: /talks/
      - text: Resume
        href: https://beatrizmilz.github.io/resume/index.pdf
      - text: My blog in Portuguese
        href: https://beatrizmilz.com/blog/
      - icon: github
        href: https://github.com/beatrizmilz/blog-en
      - icon: twitter
        href: https://twitter.com/BeaMilz

format:
  html:
    theme: journal
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/*'
    citations-hover: true
    footnotes-hover: true

editor: visual

comments:
  giscus:
    repo: beatrizmilz/blog-en
