project:
  type: website

website:
  title: "Bea Milz"
  site-url: "https://beamilz.com/"
  google-analytics: "G-2J79YYG9CZ"
  page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Beatriz Milz. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/beatrizmilz/
      - icon: twitter
        href: https://twitter.com/BeaMilz
      - icon: envelope
        href: mailto:milz.bea@gmail.com
  twitter-card:
    creator: "@beamilz"
    card-style: summary_large_image
  navbar:
    right:
      - about.qmd
      - text: Posts
        menu:
          - text: All posts
            href: /
          - text: English
            href: posts/en.qmd
          - text: Português
            href: posts/pt.qmd
          - text: Español
            href: posts/es.qmd
      - text: Series
        menu:
          - text: GitHub Actions
            href: series-gha.qmd
      - text: Talks
        menu:
          - text: English
            href: talks/en/index.qmd
          - text: Português
            href: talks/pt/index.qmd
      - text: Resume
        href: https://beatrizmilz.github.io/resume/index.pdf
      - icon: github
        href: https://github.com/beatrizmilz/blog-en
      - icon: twitter
        href: https://twitter.com/BeaMilz

format:
  html:
    smooth-scroll: true
    theme: journal
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true

editor: visual

comments:
  giscus:
    repo: beatrizmilz/blog-en
